version: '3'
services:
  mysql:
    image: mysql/mysql-server:8.0.28
    container_name: running_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretPassword2022!
      - MYSQL_DATABASE=running
      - MYSQL_USER=runninguser
      - MYSQL_PASSWORD=runningpass
    volumes:
      - mysql01:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  mysql01: {}
